const topHitters2023 = [
	{
		name: "Shohei Ohtani",
		position: "DH/P",
		battingAvg: 0.304,
		homeRuns: 46,
		RBIs: 100,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39832.png",
		id: "hit0",
	},
	{
		name: "Aaron Judge",
		position: "OF",
		battingAvg: 0.311,
		homeRuns: 44,
		RBIs: 103,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33192.png",
		id: "hit1",
	},
	{
		name: "Freddie Freeman",
		position: "1B",
		battingAvg: 0.331,
		homeRuns: 27,
		RBIs: 102,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30193.png",
		id: "hit2",
	},
	{
		name: "Mookie Betts",
		position: "OF",
		battingAvg: 0.307,
		homeRuns: 39,
		RBIs: 107,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33039.png",
		id: "hit3",
	},
	{
		name: "Matt Olson",
		position: "1B",
		battingAvg: 0.276,
		homeRuns: 54,
		RBIs: 139,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32767.png",
		id: "hit4",
	},
	{
		name: "Ronald Acuña Jr.",
		position: "OF",
		battingAvg: 0.337,
		homeRuns: 41,
		RBIs: 106,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36185.png",
		id: "hit5",
	},
	{
		name: "Kyle Schwarber",
		position: "OF",
		battingAvg: 0.197,
		homeRuns: 47,
		RBIs: 104,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33712.png",
		id: "hit6",
	},
	{
		name: "Yordan Alvarez",
		position: "DH/OF",
		battingAvg: 0.308,
		homeRuns: 31,
		RBIs: 97,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36018.png",
		id: "hit7",
	},
	{
		name: "Juan Soto",
		position: "OF",
		battingAvg: 0.281,
		homeRuns: 35,
		RBIs: 105,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36969.png",
		id: "hit8",
	},
	{
		name: "Fernando Tatis Jr.",
		position: "SS",
		battingAvg: 0.29,
		homeRuns: 25,
		RBIs: 80,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35983.png",
		id: "hit9",
	},
	{
		name: "Pete Alonso",
		position: "1B",
		battingAvg: 0.235,
		homeRuns: 42,
		RBIs: 97,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/37498.png",
		id: "hit10",
	},
	{
		name: "Bryce Harper",
		position: "DH/OF",
		battingAvg: 0.293,
		homeRuns: 18,
		RBIs: 70,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30951.png",
		id: "hit11",
	},
	{
		name: "José Ramírez",
		position: "3B",
		battingAvg: 0.282,
		homeRuns: 24,
		RBIs: 94,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32801.png",
		id: "hit12",
	},
	{
		name: "Rafael Devers",
		position: "3B",
		battingAvg: 0.277,
		homeRuns: 33,
		RBIs: 106,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33859.png",
		id: "hit13",
	},
	{
		name: "Vladimir Guerrero Jr.",
		position: "1B",
		battingAvg: 0.284,
		homeRuns: 26,
		RBIs: 89,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35002.png",
		id: "hit14",
	},
	{
		name: "Manny Machado",
		position: "3B",
		battingAvg: 0.27,
		homeRuns: 28,
		RBIs: 84,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31097.png",
		id: "hit15",
	},
	{
		name: "Nolan Arenado",
		position: "3B",
		battingAvg: 0.271,
		homeRuns: 30,
		RBIs: 101,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31261.png",
		id: "hit16",
	},
	{
		name: "Paul Goldschmidt",
		position: "1B",
		battingAvg: 0.29,
		homeRuns: 25,
		RBIs: 87,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31027.png",
		id: "hit17",
	},
	{
		name: "Bo Bichette",
		position: "SS",
		battingAvg: 0.305,
		homeRuns: 21,
		RBIs: 74,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/38904.png",
		id: "hit18",
	},
	{
		name: "Marcus Semien",
		position: "2B",
		battingAvg: 0.276,
		homeRuns: 27,
		RBIs: 93,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32146.png",
		id: "hit19",
	},
	{
		name: "Corey Seager",
		position: "SS",
		battingAvg: 0.327,
		homeRuns: 33,
		RBIs: 97,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32691.png",
		id: "hit20",
	},
	{
		name: "Trea Turner",
		position: "SS",
		battingAvg: 0.291,
		homeRuns: 27,
		RBIs: 77,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33710.png",
		id: "hit21",
	},
	{
		name: "Adolis García",
		position: "OF",
		battingAvg: 0.245,
		homeRuns: 39,
		RBIs: 107,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35537.png",
		id: "hit22",
	},
	{
		name: "Matt Chapman",
		position: "3B",
		battingAvg: 0.24,
		homeRuns: 27,
		RBIs: 76,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33857.png",
		id: "hit23",
	},
	{
		name: "Austin Riley",
		position: "3B",
		battingAvg: 0.278,
		homeRuns: 37,
		RBIs: 97,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34982.png",
		id: "hit24",
	},
	{
		name: "J.D. Martinez",
		position: "DH",
		battingAvg: 0.276,
		homeRuns: 25,
		RBIs: 88,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31065.png",
		id: "hit25",
	},
	{
		name: "Alex Bregman",
		position: "3B",
		battingAvg: 0.274,
		homeRuns: 23,
		RBIs: 89,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34886.png",
		id: "hit26",
	},
	{
		name: "Francisco Lindor",
		position: "SS",
		battingAvg: 0.254,
		homeRuns: 24,
		RBIs: 82,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32129.png",
		id: "hit27",
	},
	{
		name: "George Springer",
		position: "OF",
		battingAvg: 0.266,
		homeRuns: 22,
		RBIs: 76,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32078.png",
		id: "hit28",
	},
	{
		name: "Cedric Mullins",
		position: "OF",
		battingAvg: 0.275,
		homeRuns: 18,
		RBIs: 77,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35578.png",
		id: "hit29",
	},
	{
		name: "Dansby Swanson",
		position: "SS",
		battingAvg: 0.255,
		homeRuns: 22,
		RBIs: 72,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34895.png",
		id: "hit30",
	},
	{
		name: "Ozzie Albies",
		position: "2B",
		battingAvg: 0.267,
		homeRuns: 31,
		RBIs: 88,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33783.png",
		id: "hit31",
	},
	{
		name: "Salvador Perez",
		position: "C",
		battingAvg: 0.252,
		homeRuns: 23,
		RBIs: 74,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31127.png",
		id: "hit32",
	},
	{
		name: "Teoscar Hernández",
		position: "OF",
		battingAvg: 0.262,
		homeRuns: 26,
		RBIs: 85,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33377.png",
		id: "hit33",
	},
	{
		name: "Anthony Rizzo",
		position: "1B",
		battingAvg: 0.244,
		homeRuns: 17,
		RBIs: 56,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30782.png",
		id: "hit34",
	},
	{
		name: "Ryan Mountcastle",
		position: "1B",
		battingAvg: 0.256,
		homeRuns: 20,
		RBIs: 68,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34940.png",
		id: "hit35",
	},
	{
		name: "Joc Pederson",
		position: "OF",
		battingAvg: 0.233,
		homeRuns: 21,
		RBIs: 67,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31392.png",
		id: "hit36",
	},
	{
		name: "Yuli Gurriel",
		position: "1B",
		battingAvg: 0.267,
		homeRuns: 15,
		RBIs: 59,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36006.png",
		id: "hit37",
	},
	{
		name: "Willy Adames",
		position: "SS",
		battingAvg: 0.253,
		homeRuns: 25,
		RBIs: 75,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33675.png",
		id: "hit38",
	},
	{
		name: "Tyler O'Neill",
		position: "OF",
		battingAvg: 0.228,
		homeRuns: 15,
		RBIs: 53,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34168.png",
		id: "hit39",
	},
	{
		name: "Starling Marte",
		position: "OF",
		battingAvg: 0.287,
		homeRuns: 12,
		RBIs: 58,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30830.png",
		id: "hit40",
	},
	{
		name: "Josh Bell",
		position: "1B",
		battingAvg: 0.258,
		homeRuns: 20,
		RBIs: 67,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32517.png",
		id: "hit41",
	},
	{
		name: "Jake Cronenworth",
		position: "2B",
		battingAvg: 0.24,
		homeRuns: 13,
		RBIs: 54,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36364.png",
		id: "hit42",
	},
	{
		name: "Max Kepler",
		position: "OF",
		battingAvg: 0.22,
		homeRuns: 14,
		RBIs: 52,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31870.png",
		id: "hit43",
	},
	{
		name: "Tommy Edman",
		position: "2B",
		battingAvg: 0.263,
		homeRuns: 13,
		RBIs: 53,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39907.png",
		id: "hit44",
	},
	{
		name: "Brandon Nimmo",
		position: "OF",
		battingAvg: 0.28,
		homeRuns: 17,
		RBIs: 65,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32159.png",
		id: "hit45",
	},
	{
		name: "Christian Yelich",
		position: "OF",
		battingAvg: 0.254,
		homeRuns: 15,
		RBIs: 65,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31283.png",
		id: "hit46",
	},
	{
		name: "Ian Happ",
		position: "OF",
		battingAvg: 0.247,
		homeRuns: 17,
		RBIs: 66,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34945.png",
		id: "hit47",
	},
	{
		name: "Brandon Lowe",
		position: "2B",
		battingAvg: 0.223,
		homeRuns: 16,
		RBIs: 54,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39961.png",
		id: "hit48",
	},
	{
		name: "Jorge Polanco",
		position: "2B",
		battingAvg: 0.248,
		homeRuns: 14,
		RBIs: 61,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32525.png",
		id: "hit49",
	},
];

const topPitchers2023 = [
	{
		name: "Gerrit Cole",
		position: "SP",
		era: 2.63,
		wins: 14,
		strikeouts: 230,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32081.png",
		id: "pitch0",
	},
	{
		name: "Justin Verlander",
		position: "SP",
		era: 3.22,
		wins: 13,
		strikeouts: 185,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/6341.png",
		id: "pitch1",
	},
	{
		name: "Max Scherzer",
		position: "SP",
		era: 3.27,
		wins: 13,
		strikeouts: 203,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/28976.png",
		id: "pitch2",
	},
	{
		name: "Corbin Burnes",
		position: "SP",
		era: 3.46,
		wins: 12,
		strikeouts: 210,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39878.png",
		id: "pitch3",
	},
	{
		name: "Zack Wheeler",
		position: "SP",
		era: 3.55,
		wins: 12,
		strikeouts: 220,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/31267.png",
		id: "pitch4",
	},
	{
		name: "Shane Bieber",
		position: "SP",
		era: 3.49,
		wins: 11,
		strikeouts: 200,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/40912.png",
		id: "pitch5",
	},
	{
		name: "Walker Buehler",
		position: "SP",
		era: 3.12,
		wins: 10,
		strikeouts: 165,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39251.png",
		id: "pitch6",
	},
	{
		name: "Lucas Giolito",
		position: "SP",
		era: 3.89,
		wins: 11,
		strikeouts: 185,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32697.png",
		id: "pitch7",
	},
	{
		name: "Julio Urías",
		position: "SP",
		era: 3.29,
		wins: 14,
		strikeouts: 170,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33223.png",
		id: "pitch8",
	},
	{
		name: "Carlos Rodón",
		position: "SP",
		era: 3.55,
		wins: 12,
		strikeouts: 175,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33696.png",
		id: "pitch9",
	},
	{
		name: "Aaron Nola",
		position: "SP",
		era: 3.59,
		wins: 13,
		strikeouts: 215,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33709.png",
		id: "pitch10",
	},
	{
		name: "Robbie Ray",
		position: "SP",
		era: 3.76,
		wins: 11,
		strikeouts: 192,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32175.png",
		id: "pitch11",
	},
	{
		name: "Chris Sale",
		position: "SP",
		era: 3.58,
		wins: 10,
		strikeouts: 185,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30948.png",
		id: "pitch12",
	},
	{
		name: "Brandon Woodruff",
		position: "SP",
		era: 3.45,
		wins: 12,
		strikeouts: 195,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/37515.png",
		id: "pitch13",
	},
	{
		name: "Dylan Cease",
		position: "SP",
		era: 3.91,
		wins: 13,
		strikeouts: 225,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34943.png",
		id: "pitch14",
	},
	{
		name: "Sandy Alcantara",
		position: "SP",
		era: 3.88,
		wins: 10,
		strikeouts: 195,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35241.png",
		id: "pitch15",
	},
	{
		name: "Framber Valdez",
		position: "SP",
		era: 3.6,
		wins: 12,
		strikeouts: 170,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36581.png",
		id: "pitch16",
	},
	{
		name: "Logan Webb",
		position: "SP",
		era: 3.28,
		wins: 11,
		strikeouts: 165,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/41216.png",
		id: "pitch17",
	},
	{
		name: "Max Fried",
		position: "SP",
		era: 2.87,
		wins: 15,
		strikeouts: 180,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32685.png",
		id: "pitch18",
	},
	{
		name: "Clayton Kershaw",
		position: "SP",
		era: 3.21,
		wins: 10,
		strikeouts: 135,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/28963.png",
		id: "pitch19",
	},
	{
		name: "Kevin Gausman",
		position: "SP",
		era: 3.81,
		wins: 10,
		strikeouts: 185,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/32667.png",
		id: "pitch20",
	},
	{
		name: "Luis Castillo",
		position: "SP",
		era: 3.55,
		wins: 12,
		strikeouts: 165,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/35124.png",
		id: "pitch21",
	},
	{
		name: "Pablo López",
		position: "SP",
		era: 3.61,
		wins: 11,
		strikeouts: 160,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39671.png",
		id: "pitch22",
	},
	{
		name: "Freddy Peralta",
		position: "SP",
		era: 3.94,
		wins: 10,
		strikeouts: 165,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39825.png",
		id: "pitch23",
	},
	{
		name: "Joe Musgrove",
		position: "SP",
		era: 3.79,
		wins: 12,
		strikeouts: 180,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/34848.png",
		id: "pitch24",
	},
	{
		name: "Shane McClanahan",
		position: "SP",
		era: 3.5,
		wins: 14,
		strikeouts: 190,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/41199.png",
		id: "pitch25",
	},
	{
		name: "Blake Snell",
		position: "SP",
		era: 3.38,
		wins: 10,
		strikeouts: 210,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33748.png",
		id: "pitch26",
	},
	{
		name: "Zac Gallen",
		position: "SP",
		era: 3.48,
		wins: 14,
		strikeouts: 180,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/39910.png",
		id: "pitch27",
	},
	{
		name: "Nestor Cortes",
		position: "SP",
		era: 3.83,
		wins: 12,
		strikeouts: 170,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/36480.png",
		id: "pitch28",
	},
	{
		name: "Tyler Glasnow",
		position: "SP",
		era: 3.32,
		wins: 8,
		strikeouts: 115,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/33190.png",
		id: "pitch29",
	},
];
const topRelievers2023 = [
	{
		name: "Edwin Díaz",
		position: "RP",
		era: 1.32,
		saves: 36,
		strikeouts: 123,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/35394.png&w=350&h=254",
		id: "rel0",
	},
	{
		name: "Josh Hader",
		position: "RP",
		era: 1.6,
		saves: 33,
		strikeouts: 115,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/32760.png",
		id: "rel1",
	},
	{
		name: "Liam Hendriks",
		position: "RP",
		era: 2.42,
		saves: 34,
		strikeouts: 100,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/31755.png",
		id: "rel2",
	},
	{
		name: "Emmanuel Clase",
		position: "RP",
		era: 1.98,
		saves: 40,
		strikeouts: 80,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/41743.png&w=350&h=254",
		id: "rel3",
	},
	{
		name: "Ryan Pressly",
		position: "RP",
		era: 2.77,
		saves: 32,
		strikeouts: 80,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/33072.png",
		id: "rel4",
	},
	{
		name: "Raisel Iglesias",
		position: "RP",
		era: 2.75,
		saves: 30,
		strikeouts: 90,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/33618.png&w=350&h=254",
		id: "rel5",
	},
	{
		name: "Devin Williams",
		position: "RP",
		era: 1.85,
		saves: 29,
		strikeouts: 95,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/33224.png&w=350&h=254",
		id: "rel6",
	},
	{
		name: "Kenley Jansen",
		position: "RP",
		era: 3.05,
		saves: 31,
		strikeouts: 85,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/29630.png",
		id: "rel7",
	},
	{
		name: "Aroldis Chapman",
		position: "RP",
		era: 3.18,
		saves: 28,
		strikeouts: 88,
		imageUrl: "https://a.espncdn.com/i/headshots/mlb/players/full/30442.png",
		id: "rel8",
	},
	{
		name: "Jordan Romano",
		position: "RP",
		era: 2.6,
		saves: 35,
		strikeouts: 85,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/36380.png",
		id: "rel9",
	},
	{
		name: "Craig Kimbrel",
		position: "RP",
		era: 3.41,
		saves: 22,
		strikeouts: 90,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/30653.png",
		id: "rel10",
	},
	{
		name: "Blake Treinen",
		position: "RP",
		era: 2.8,
		saves: 19,
		strikeouts: 75,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/32185.png",
		id: "rel11",
	},
	{
		name: "Taylor Rogers",
		position: "RP",
		era: 3.34,
		saves: 25,
		strikeouts: 82,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/33671.png&w=350&h=254",
		id: "rel12",
	},
	{
		name: "Scott Barlow",
		position: "RP",
		era: 2.55,
		saves: 24,
		strikeouts: 95,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/32156.png",
		id: "rel13",
	},
	{
		name: "David Bednar",
		position: "RP",
		era: 2.23,
		saves: 20,
		strikeouts: 80,
		imageUrl:
			"https://a.espncdn.com/combiner/i?img=/i/headshots/mlb/players/full/38303.png",
		id: "rel14",
	},
];

const getTopRelievers = (req, res) => {
	res.json(topRelievers2023);
};

const getTopHitters = (req, res) => {
	res.json(topHitters2023);
};

const getTopStartingPitchers = (req, res) => {
	res.json(topPitchers2023);
};

module.exports = { getTopRelievers, getTopHitters, getTopStartingPitchers };
